; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)

define i32 @compute() {
entry:
	%a_addr = alloca i32
	%t0 = mul i32 4, 2
	%t1 = add i32 3, %t0
	store i32 %t1, i32* %a_addr
	%b_addr = alloca i32
	%t2 = load i32, i32* %a_addr
	%t3 = sub i32 %t2, 1
	store i32 %t3, i32* %b_addr
	%t4 = load i32, i32* %a_addr
	%t5 = load i32, i32* %b_addr
	%t6 = add i32 %t4, %t5
	ret i32 %t6
}


