; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define void @open_file(i1 %ok) {
entry:
	; TODO: DeferStatement
	br i1 %ok, label %lbl0, label %lbl1
lbl0:
	ret void
lbl1:
	%t2 = call i32 @println(i32 0)
	ret void
}


