; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define i32 @bind(i32 %port) {
entry:
	ret i32 0
}

define void @run() {
entry:
	%res_addr = alloca i32
	; TODO: unsupported initial value (TryExpression)
	; TODO: skipped call (FunctionCall)
	ret void
}
