; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define void @make_int() {
entry:
	%x_addr = alloca i32
	store i32 0, i32* %x_addr
	%t0 = load i32, i32* %x_addr
	ret void %t0
}
