; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define i32 @double(i32 %x) {
entry:
	%t0 = mul i32 %x, 2
	ret i32 %t0
}

define void @main() {
entry:
	%x_addr = alloca i32
	%t0 = call i32 @double(i32 5)
	store i32 %t0, i32* %x_addr
	%t1 = call i32 @println(i32 0)
	ret void
}
