; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define void @main() {
entry:
	%name_addr = alloca i32
	store i32 0, i32* %name_addr
	%age_addr = alloca i32
	store i32 22, i32* %age_addr
	; TODO: skipped call (FunctionCall)
	; TODO: skipped call (FunctionCall)
	; TODO: skipped call (FunctionCall)
	ret void
}
