; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define void @check_status(i32 %code) {
entry:
	%s_addr = alloca i32
	store i32 %code, i32* %s_addr
	ret void
}
