; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define i32 @get_val(i32 %ptr) {
entry:
	%t0 = load i32, i32* %ptr
	ret i32 %t0
}

define void @main() {
entry:
	%x_addr = alloca i32
	store i32 10, i32* %x_addr
	%y_addr = alloca i32
	%t0 = load i32, i32* %x_addr
	%t1 = call i32 @get_val(i32 %t0)
	store i32 %t1, i32* %y_addr
	%t2 = call i32 @println(i32 0)
	ret void
}
