; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define i32 @add(i32 %a, i32 %b) {
entry:
	%t0 = add i32 %a, %b
	ret i32 %t0
}

define i1 @is_even(i32 %n) {
entry:
	%t0 = srem i32 %n, 2
	%t1 = icmp eq i32 %t0, 0
	ret i1 %t1
}

define void @main() {
entry:
	%x_addr = alloca i32
	store i32 10, i32* %x_addr
	%y_addr = alloca i32
	store i32 20, i32* %y_addr
	%result_addr = alloca i32
	%t0 = load i32, i32* %x_addr
	%t1 = load i32, i32* %y_addr
	%t2 = call i32 @add(i32 %t0, i32 %t1)
	store i32 %t2, i32* %result_addr
	%t3 = load i32, i32* %result_addr
	%t4 = icmp eq i32 %t3, 30
	br i1 %t4, label %lbl5, label %lbl7
lbl5:
	%t8 = load i32, i32* %result_addr
	%t9 = add i32 %t8, 1
	store i32 %t9, i32* %result_addr
	br label %lbl6
lbl7:
	store i32 0, i32* %result_addr
	br label %lbl6
lbl6:
	%counter_addr = alloca i32
	store i32 0, i32* %counter_addr
	br label %lbl10
lbl10:
	%t12 = load i32, i32* %counter_addr
	%t13 = icmp eq i32 %t12, 100
	br i1 %t13, label %lbl14, label %lbl15
lbl14:
	br label %lbl11
lbl15:
	%t16 = load i32, i32* %counter_addr
	%t17 = add i32 %t16, 1
	store i32 %t17, i32* %counter_addr
	br label %lbl10
lbl11:
	%t18 = call i32 @println(i32 0)
	ret void
}


