; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)

define i1 @check(i32 %n) {
entry:
	%t0 = icmp sgt i32 %n, 0
	br i1 %t0, label %lbl1, label %lbl3
lbl1:
	ret i1 1
lbl3:
	ret i1 0
}


