; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

; module Network
define i32 @bind(i32 %port) {
entry:
	ret i32 0
}

define void @handle_conn() {
entry:
	; TODO: DeferStatement
	%s_addr = alloca i32
	store i32 0, i32* %s_addr
	; TODO: MatchStatement
	%items_addr = alloca i32
	; TODO: unsupported initial value (ArrayLiteral)
	br label %lbl0
lbl0:
	; TODO: skipped call (FunctionCall)
	br label %lbl0
lbl1:
	%res_addr = alloca i32
	; TODO: unsupported initial value (TryExpression)
	ret void
}

define void @main() {
entry:
	%t0 = call i32 @handle_conn()
	%t1 = call i32 @exit(i32 0)
	ret void
}


