; Generated by Razen compiler — LLVM IR backend
source_filename = "razen_output"

declare i32 @printf(i8* nocapture, ...)
declare i32 @puts(i8* nocapture)
declare i32 @print(i32)
declare i32 @println(i32)
declare i32 @exit(i32)
declare i32 @assert(i32)
declare i32 @panic(i8*)

define i32 @divide(i32 %a, i32 %b) {
entry:
	%t0 = icmp ne i32 %b, 0
	%t1 = call i32 @assert(i32 %t0)
	%t2 = sdiv i32 %a, %b
	ret i32 %t2
}

define void @main() {
entry:
	%x_addr = alloca i32
	%t0 = call i32 @divide(i32 10, i32 2)
	store i32 %t0, i32* %x_addr
	%t1 = call i32 @println(i32 0)
	ret void
}
