// llvm_convert.zig — top-level Razen → LLVM IR converter.
//
// Mirrors the tutorial's llvm_convert.zig, adapted to Razen's codebase.
// Call convert() with the AST; it returns an owned slice of LLVM IR text.

const std = @import("std");
const node_mod = @import("../../ast/node.zig");
const ASTNode = node_mod.ASTNode;
const ASTNodeType = node_mod.ASTNodeType;
const lexer = @import("../../lexer/lexer.zig");
const convert_data_mod = @import("../convert_data.zig");
const ConvertData = convert_data_mod.ConvertData;
const StringBuilder = convert_data_mod.StringBuilder;
const ConvertError = @import("../errors.zig").ConvertError;
const llvm_function = @import("llvm_function.zig");
const std_fmt = @import("../../std/fmt.zig");
const std_os = @import("../../std/os.zig");
const std_debug = @import("../../std/debug.zig");
const print = std.debug.print;
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

pub fn convert(
    allocator: *Allocator,
    ast_nodes: *ArrayList(*ASTNode),
    source: []const u8,
) ConvertError![]u8 {
    _ = source;

    print("\t{s}Converting to LLVM IR{s}\t\t", .{ lexer.GREY, lexer.RESET });

    if (ast_nodes.items.len == 0) return ConvertError.No_AST_Nodes;

    var generated_code = StringBuilder.init(allocator.*) catch return ConvertError.Out_Of_Memory;

    const var_types = std.StringHashMap([]const u8).init(allocator.*);
    const union_registry = std.StringHashMap(std.StringHashMap([]const u8)).init(allocator.*);
    const deferred_stmts = std.ArrayList(*ASTNode).initCapacity(allocator.*, 0) catch return ConvertError.Out_Of_Memory;
    const global_constants = std.StringHashMap([]const u8).init(allocator.*);

    var convert_data = ConvertData{
        .ast_nodes = ast_nodes,
        .generated_code = &generated_code,
        .var_types = var_types,
        .deferred_stmts = deferred_stmts,
        .union_registry = union_registry,
        .global_constants = global_constants,
    };

    // ── module preamble ────────────────────────────────────────────────────
    generated_code.appendLine(allocator, "; Generated by Razen compiler — LLVM IR backend") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "source_filename = \"razen_output\"") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "") catch return ConvertError.Out_Of_Memory;
    // Standard libc declarations for builtins and std library
    generated_code.appendLine(allocator, "declare i32 @printf(i8* nocapture, ...)") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "declare i32 @puts(i8* nocapture)") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "declare void @exit(i32)") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "declare void @abort()") catch return ConvertError.Out_Of_Memory;
    generated_code.appendLine(allocator, "") catch return ConvertError.Out_Of_Memory;

    // ── std library LLVM IR definitions ─────────────────────────────────────
    for ([_][]const u8{ std_fmt.ir, std_os.ir, std_debug.ir }) |ir| {
        generated_code.append(allocator, ir) catch return ConvertError.Out_Of_Memory;
        generated_code.append(allocator, "\n") catch return ConvertError.Out_Of_Memory;
    }
    generated_code.appendLine(allocator, "") catch return ConvertError.Out_Of_Memory;

    // ── walk top-level nodes ───────────────────────────────────────────────
    const node_count = ast_nodes.items.len;
    while (convert_data.node_index < node_count) {
        const before = convert_data.node_index;

        processGlobalNode(allocator, &convert_data) catch |err| {
            print("{s}LLVM codegen error{s}\n", .{ lexer.RED, lexer.RESET });
            return err;
        };

        // Safety advance — avoid infinite loop if a handler doesn't advance
        if (before == convert_data.node_index) {
            convert_data.node_index += 1;
        }
    }

    print("{s}Done{s}\n", .{ lexer.CYAN, lexer.RESET });

    return generated_code.toOwnedSlice(allocator) catch return ConvertError.Out_Of_Memory;
}

fn processGlobalNode(
    allocator: *Allocator,
    convert_data: *ConvertData,
) ConvertError!void {
    convert_data.error_function = "processGlobalNode";

    const node = convert_data.getNode() orelse return ConvertError.Node_Is_Null;

    switch (node.node_type) {
        // ── functions ──────────────────────────────────────────────────────
        .FunctionDeclaration, .ExtDeclaration => {
            try llvm_function.processFunctionDeclaration(allocator, convert_data, node);
            convert_data.node_index += 1;
        },

        // ── module / use — no IR output ────────────────────────────────────
        .ModuleDeclaration => {
            if (node.token) |tok| {
                convert_data.generated_code.appendFmt(allocator, "; module {s}\n", .{tok.value}) catch return ConvertError.Out_Of_Memory;
            }
            convert_data.node_index += 1;
        },
        .UseDeclaration => {
            convert_data.node_index += 1;
        },

        // ── global constants / variables — track for identifier resolution ──
        .ConstDeclaration, .VarDeclaration => {
            if (node.token) |tok| {
                if (node.right != null and node.right.?.node_type == .IntegerLiteral) {
                    if (node.right.?.token) |val_tok| {
                        convert_data.global_constants.put(tok.value, val_tok.value) catch {};
                    }
                }
            }
            convert_data.node_index += 1;
        },

        // ── types — emit IR struct types later; skip for now ───────────────
        .StructDeclaration,
        .EnumDeclaration,
        .UnionDeclaration,
        .ErrorDeclaration,
        .TypeAliasDeclaration,
        .BehaveDeclaration,
        .Comment,
        => {
            convert_data.node_index += 1;
        },

        // ── everything else — skip gracefully ──────────────────────────────
        else => {
            convert_data.node_index += 1;
        },
    }
}
