const std = @import("std");

pub const SemanticError = error{
    UndeclaredVariable,
    AlreadyDeclared,
    ImmutableAssignment,
    ArgumentCountMismatch,
    ArgumentTypeMismatch,
    ReturnTypeMismatch,
    TypeMismatch,
    IfConditionNotBool,
    LoopConditionNotBool,
    BreakOutsideLoop,
    SkipOutsideLoop,
    MemberNotFound,
    NotAStruct,
    NotAnEnum,
    NotAUnion,
    NotAFunction,
    NotACallable,
    UndeclaredType,
    InvalidBinaryOp,
    MissingReturn,
    WrongReturnType,
    InternalError,
    OutOfMemory,
};
